# -*- coding: utf-8 -*-
"""Gizzie_CapstoneProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18pYIcVd3KSFPVljY_2qYZhHNxJSsKbSz

Cleaning Original Data Set
"""

import pandas as pd

tekmart_df = pd.read_csv("tekmartdata.csv")

"""Searching for null values
(fill the unknown customer reviews with n/a because a lack of a customer review doesn't necessarily require that given data point to be excluded from the entire set, and will filter that out later)
"""

#na values
na_counts = tekmart_df.isna().sum()
print(tekmart_df.dtypes)


print(na_counts)

#dropping rows with missing values that are necessary to make conclusions
tekmart_df = tekmart_df.dropna(subset="Quantity")
tekmart_df = tekmart_df.dropna(subset="Purchase_Date")
tekmart_df = tekmart_df.dropna(subset="Shipping_Cost_USD")
tekmart_df = tekmart_df.dropna(subset="Unit_Price_USD")
tekmart_df = tekmart_df.dropna(subset="Country")
tekmart_df = tekmart_df.dropna(subset="Purchase_ID")
tekmart_df = tekmart_df.dropna(subset="Customer_ID")
tekmart_df = tekmart_df.dropna(subset="Supplier_Type")
tekmart_df = tekmart_df.dropna(subset="Unit_Cost_USD")
tekmart_df = tekmart_df.dropna(subset="Brand")
tekmart_df = tekmart_df.dropna(subset="Product_Name")
tekmart_df = tekmart_df.dropna(subset="Satisfaction_Rating")
tekmart_df = tekmart_df.dropna(subset="City")
tekmart_df = tekmart_df.dropna(subset="State_or_Province")
tekmart_df = tekmart_df.dropna(subset = "Supplier_Name")

tekmart_df['Customer_Review'] = tekmart_df['Customer_Review'].fillna('n/a')

print(tekmart_df.isna().sum())

#delete FULL ROW duplicates, will see that split single orders into multiple rows
print(tekmart_df.duplicated().sum())

#ensuring satisfaction rating max=10
tekmart_df["Satisfaction_Rating"].max()

"""Checking if all rows with significant null values eliminated"""

#checking work
print(tekmart_df.shape)
print(tekmart_df.info())

"""Adding in New Columns"""

# Profit per order
tekmart_df["Profit_Per_Order"] = (
    ((tekmart_df["Unit_Price_USD"]
    - tekmart_df["Unit_Cost_USD"])
    * tekmart_df["Quantity"] )
    - tekmart_df["Shipping_Cost_USD"]
)

# Revenue per order
tekmart_df["Revenue_Per_Order"] = (
    tekmart_df["Unit_Price_USD"] * tekmart_df["Quantity"]
)

# Year column
tekmart_df["Year"] = pd.to_datetime(tekmart_df["Purchase_Date"]).dt.year

#Month/Year column
tekmart_df["Month/Year"] = pd.to_datetime(tekmart_df["Purchase_Date"]).dt.to_period("M")

# Profit per year
tekmart_df["Profit_per_Year"] = tekmart_df.groupby("Year")["Profit_Per_Order"].transform("sum")

# Revenue per year
tekmart_df["Revenue_per_Year"] = tekmart_df.groupby("Year")["Revenue_Per_Order"].transform("sum")

print(tekmart_df.info())

print(tekmart_df["Month/Year"])
tekmart_df["Month/Year"].to_csv('monthyear.csv')

"""------

Creating a product type column


*   noticed that the first word of each product name could easily be used to classify what type of product it was
*   decided on this approach after a failed attempt at NL (my model was consistently clustering together iphones and cables, which would not work for this project)
* manually categorized each item
* lastly, checked to ensure no null values in the new column and no "other" values
"""

#looking at only the first word
tekmart_df['first_word'] = tekmart_df['Product_Name'].str.extract(r'^(\w+)')

#looking for distinct product names
tekmart_df['first_word'].nunique()

# listing of distinct first words
tekmart_df['first_word'].value_counts().head(23)

#wanted to ensure Galaxy first work goes to mobile phone, while Galaxy Tab goes to ipad
tekmart_df['Product_Name'] = tekmart_df['Product_Name'].str.replace(
    r'^Galaxy Tab',
    'GalaxyTab',
    regex=True
)

#creating product categories
def get_product_type(name):
    name = str(name).lower()

    if any(x in name for x in ['iphone', 'galaxy', 'mi', 'mate', 'oneplus', 'pixel']):
        return 'Mobile Phone'

    if any(x in name for x in ['cyber']):
        return 'Camera'

    if any(x in name for x in ['ipod']):
        return 'iPod'

    if any(x in name for x in ['vivo', 'watch', 'charge']):
        return 'Watch'

    if any(x in name for x in ['lightning', 'usb']):
        return 'Cable'

    if any(x in name for x in ['ipad', 'fire', 'galaxytab']):
        return 'iPad'

    if any(x in name for x in ['wireless','power']):
        return 'Accessories'

    if any(x in name for x in ['buds', 'qc', 'airpods']):
        return 'Audio'

    if any(x in name for x in ['echo', 'nest', 'walkman']):
        return 'Smart Home Device'

    return 'other'

tekmart_df['Product_Types'] = tekmart_df['Product_Name'].apply(get_product_type)

#checking work
tekmart_df['Product_Types'].isna().sum()

tekmart_df["Product_Types"].value_counts().get("other", 0)

#double checking work
#This is trying to check my work to make sure no values have gone unchategorized and to ensure that the code doesn't miscategorize products with the same first word but that are different product types
tekmart_df['no_numbers'] = tekmart_df['Product_Name'].str.replace(r'\d+', '', regex=True)

tekmart_df['clean_name'] = (
    tekmart_df['no_numbers']
        .str.replace(r'[^A-Za-z\s]', '', regex=True)
        .str.strip()
        .str.lower()
)

tekmart_df['Galaxy'] = tekmart_df['clean_name'].str.split().str[0]

unique_counts = tekmart_df.groupby('Galaxy')['clean_name'].nunique()

print(unique_counts)

grouped_names = tekmart_df.groupby('Galaxy')['clean_name'].unique()
print(grouped_names)

tekmart_df.to_csv('tekmartdatanew.csv')
#last step, DONT run until finished

"""Creating a supplier DataFrame with the intention of finding profit by supplier and shipping cost by supplier (to fulfill consultants' requests)"""

#Supplier DataFrame
supplier_df = (
    tekmart_df.groupby("Supplier_Name")
      .agg(TotalProfit=("Profit_Per_Order", "sum"),
           AvgProfit=("Profit_Per_Order", "mean"),
           NumProducts=("Profit_Per_Order", "count"),
           TotalShippingCost=("Shipping_Cost_USD", "sum"),
           AvgSatisfaction=("Satisfaction_Rating", "mean"))
      .reset_index(),

)

print(supplier_df)

supplier_df[0].to_csv('supplier_data.csv')

"""Creating a brand DataFrame with the intention of looking at profits by brand (to fulfill consultants' requests)"""

#Brand DataFrame
brand_df = (
    tekmart_df.groupby("Brand")
      .agg(TotalProfit=("Profit_Per_Order", "sum"),
           AvgProfit=("Profit_Per_Order", "mean"),
           NumProducts=("Profit_Per_Order", "count"),
           AvgSatisfaction=("Satisfaction_Rating", "mean"))
      .reset_index()
)
print(brand_df)
brand_df.to_csv('brand.csv')

"""City DataFrame with the intention to look at total profit and sales (to fulfill consultants' requests)"""

#City DataFrame
city_df = (
    tekmart_df.groupby("City")
    .agg(TotalProfit=("Profit_Per_Order", "sum"),
         AvgProfit=("Profit_Per_Order", "mean"))
    .reset_index()
)
print(city_df)
city_df.to_csv('city_data.csv')

"""Country DataFrame with the intention to look at total profits and sales(to fulfill consultants' requests)"""

country_df = (
    tekmart_df.groupby("Country")
    .agg(TotalProfit=("Profit_Per_Order", "sum"), TotalSales=("Quantity", "sum"))
    .reset_index()
)
print(country_df)
country_df.to_csv('city_data.csv')

"""Creating a continent column (to fulfill consultants' requests after I had originally created more columns)
* creating continent DataFrame
* exporting the continent column to add to tekmartdata in google sheets (where working with consultants)
"""

continent_map = {
    "Australia":"Oceainia",
    "Brazil":"South America",
    "Canada":"North America",
    "China":"Asia",
    "France":"Europe",
    "Germany":"Europe",
    "India":"Asia",
    "Italy":"Europe",
    "Japan" :"Asia",
    "Mexico":"South America",
    "Nigeria":"Africa",
    "Singapore":"Asia",
    "South Africa":"Africa",
    "Spain":"Europe",
    "United Arab Emirates":"Asia",
    "United Kingdom":"Europe",
    "United States":"North America"
}


tekmart_df["Continent"] = tekmart_df["Country"].map(continent_map)
print(tekmart_df["Continent"])
tekmart_df["Continent"].to_csv('continent.csv')

#checking null values
tekmart_df['Continent'].isna().sum()

"""Creating continent DataFrame with the intention to look at total profit and shipping costs (to fulfill consultants' requests)"""

continent_df = (
    tekmart_df.groupby("Continent").agg(
        TotalProfit=("Profit_Per_Order", "sum"), TotalShippingCost=("Shipping_Cost_USD", "sum"))
)

continent_df.to_csv('continent_data.csv')

"""Creating product types DataFrame with the intention to look at total profits, quantity, and the most popular city for each category (to fulfill consultants' requests)"""

popular_city = (
    tekmart_df
    .groupby("Product_Types")["City"]
    .agg(lambda x: x.value_counts().idxmax())
)


product_type_df = (
    tekmart_df.groupby("Product_Types")
    .agg(TotalProfit=("Profit_Per_Order", "sum"),
         TotalQuantity=("Quantity", "sum"))
    .reset_index()
)

product_type_df = product_type_df.merge(
    popular_city.rename("Most_Popular_City"),
    on="Product_Types",
    how="left"
)

print(product_type_df)
product_type_df.to_csv('product_type_data.csv')

"""----

Experimenting with profit over time graphs (played around with by year and month, but didn't end up using anythign found in these graphs to make any conclusions)
"""

range = tekmart_df["Month/Year"].between("2020-01", "2021-12")
range_df = tekmart_df[range]
profit_over_time = range_df.groupby("Month/Year")["Profit_Per_Order"].sum()

import matplotlib.pyplot as plt

plt.figure(figsize=(12,6))
profit_over_time.plot()
plt.title("Profit Over Time")
plt.xlabel("Date")
plt.ylabel("Total Profit")
plt.grid (which="minor", alpha=0.1)
plt.grid(True)
plt.show()

peak_x = profit_over_time.idxmax()   # date of max value
peak_y = profit_over_time.max()


print((peak_x, peak_y))

range = tekmart_df["Month/Year"].between("2022-01", "2023-12")
range_df = tekmart_df[range]
profit_over_time = range_df.groupby("Month/Year")["Profit_Per_Order"].sum()

import matplotlib.pyplot as plt

plt.figure(figsize=(12,6))
profit_over_time.plot()
plt.title("Profit Over Time")
plt.xlabel("Date")
plt.ylabel("Total Profit")
plt.grid (which="minor", alpha=0.1)
plt.grid(True)
plt.show()

peak_x = profit_over_time.idxmax()   # date of max value
peak_y = profit_over_time.max()


print((peak_x, peak_y))

"""the above shows that the first highpoint post 2019 was in demeber of 2021, thus when looking at customer reviews we need to look for bad ones between the range of dec 2021 to dec 2023

"""

mobile_phone_df = (
    tekmart_df[tekmart_df["Product_Types"] == "Mobile Phone"]
)

mobile_phone_18_21 = mobile_phone_df[
    (mobile_phone_df["Year"] >= 2018) &
    (mobile_phone_df["Year"] <= 2025)
    ].copy() # Added .copy() to prevent SettingWithCopyWarning

mobile_phone_18_21["Purchase_Date"] = pd.to_datetime(mobile_phone_18_21["Purchase_Date"]) # Convert to datetime
mobile_phone_18_21["Year"] = mobile_phone_18_21["Purchase_Date"].dt.to_period("Y")
mobile_sales_monthly = (
    mobile_phone_18_21.groupby("Year")["Quantity"].sum()
)

plt.figure(figsize=(12,6))
mobile_sales_monthly.plot()

plt.title("Yearly Mobile Phone Sales (2018–2025)")
plt.xlabel("Year")
plt.ylabel("Quantity Sold", rotation=0,labelpad=20)
plt.grid(True)
plt.show()

"""iPad Sales 2018-2025"""

ipad_df = tekmart_df[tekmart_df["Product_Types"] == "iPad"]

ipad_df["Purchase_Date"] = pd.to_datetime(ipad_df["Purchase_Date"])

ipad_18_21 = ipad_df[
    (ipad_df["Purchase_Date"].dt.year >= 2018) &
    (ipad_df["Purchase_Date"].dt.year <= 2025)
    ]

ipad_18_21["Year"] = ipad_18_21["Purchase_Date"].dt.to_period("Y")
ipad_sales_yearly = (
    ipad_18_21.groupby("Year")["Quantity"].sum()
)

plt.figure(figsize=(12,6))
mobile_sales_monthly.plot()

plt.title("Yearly iPad Sales (2018–2025)")
plt.xlabel("Yearly")
plt.ylabel("Quantity Sold", rotation=0,labelpad=25)
plt.grid(True)
plt.show()

"""Yearly Smart Home Device Sales 2018-2025"""

shd_df = tekmart_df[tekmart_df["Product_Types"] == "Smart Home Device"].copy()

shd_df["Purchase_Date"] = pd.to_datetime(shd_df["Purchase_Date"])

shd_18_21 = shd_df[
    (shd_df["Purchase_Date"].dt.year >= 2018) &
    (shd_df["Purchase_Date"].dt.year <= 2025)
    ].copy()

shd_18_21["Year"] = shd_18_21["Purchase_Date"].dt.to_period("Y")
shd_sales_yearly = (
    shd_18_21.groupby("Year")["Quantity"].sum()
)

plt.figure(figsize=(12,6))
mobile_sales_monthly.plot()

plt.title("Yearly Smart Home Device Sales (2018–2025)")
plt.xlabel("Year")
plt.ylabel("Quantity Sold", rotation=0,labelpad=20)
plt.grid(True)
plt.show()

"""Yearly Watch Sales 2018-2025"""

watches_df = tekmart_df[tekmart_df["Product_Types"] == "Watch"].copy()

watches_df["Purchase_Date"] = pd.to_datetime(watches_df["Purchase_Date"])

watches_18_21 = watches_df[
    (watches_df["Purchase_Date"].dt.year >= 2018) &
    (watches_df["Purchase_Date"].dt.year <= 2025)
    ].copy()

watches_18_21["Year"] = watches_18_21["Purchase_Date"].dt.to_period("Y")
watch_sales_yearly = (
    watches_18_21.groupby("Year")["Quantity"].sum()
)

plt.figure(figsize=(12,6))
mobile_sales_monthly.plot()

plt.title("Yearly Watch Sales (2018–2025)")
plt.xlabel("Year")
plt.ylabel("Quantity Sold", rotation=0,labelpad=20)
plt.grid(True)
plt.show()

"""Yearly Accessories Sales 2018-2025"""

ac_df = tekmart_df[tekmart_df["Product_Types"] == "Accessories"].copy()

ac_df["Purchase_Date"] = pd.to_datetime(ac_df["Purchase_Date"])

ac_18_21 = ac_df[
    (ac_df["Purchase_Date"].dt.year >= 2018) &
    (ac_df["Purchase_Date"].dt.year <= 2025)
    ].copy()

ac_18_21["Year"] = ac_18_21["Purchase_Date"].dt.to_period("Y")
ac_sales_yearly = (
    watches_18_21.groupby("Year")["Quantity"].sum()
)

plt.figure(figsize=(12,6))
mobile_sales_monthly.plot()

plt.title("Yearly Accessories Sales (2018–2025)")
plt.xlabel("Year")
plt.ylabel("Quantity Sold", rotation=0,labelpad=20)
plt.grid(True)
plt.show()

"""------

Counting Quantities for Product Types (requested by consultants)
"""

#total of each product type
tekmart_df.groupby("Product_Types")['Quantity'].sum()

"""----

Using NLP to look at customer reviews
* chose k=3 to get  clusters of good, average, and bad customer reviews
* looked at Tekmart profit/time graph to find where Tekmart profits began to dip after 2020
* identified 2023 as the key date, so needed bad customer reviews from 2021-2023
* created a new DataFrame of those bad reviews, excluding any rows that had empty customer reviews, and identified the 3 most common product names in the DataFrame
* dropped the "worst_reviews_df" into sheets for better visualization and grouping to come up with post-2020 regrowth strategy
"""

#Using Natural Language Processing to look at customer reviews for specific brands
import numpy as np
tekmart_df = tekmart_df.loc[:10000]

# Ensure 'Customer_Review' column contains only strings and handle potential NaNs
# Replace any remaining NaN (which are floats) with 'n/a' and then convert the column to string type.
tekmart_df['Customer_Review'] = tekmart_df['Customer_Review'].fillna('n/a').astype(str)

!pip install gensim

from gensim.models import Word2Vec

import nltk
nltk.download('punkt')
nltk.download('punkt_tab')
from nltk.tokenize import word_tokenize

documents = [word_tokenize(text) for text in tekmart_df['Customer_Review']]
model = Word2Vec(documents, min_count=1, vector_size=100, window=5)

# Define function to create sentence vectors and apply it
def create_sentence_vector(sentence, model):
    word_vectors = []
    for word in word_tokenize(sentence):
        try:
            word_vectors.append(model.wv[word])
        except KeyError:
            pass
    if not word_vectors:
        return np.zeros(model.vector_size)
    return np.mean(word_vectors, axis=0)

tekmart_df['sentence_vector'] = tekmart_df['Customer_Review'].apply(lambda x: create_sentence_vector(x, model))

from sklearn.decomposition import PCA

# Apply PCA
pca = PCA(n_components=2)  # Reduce to 2 principal components
sentence_vectors_2d = pca.fit_transform(np.stack(tekmart_df['sentence_vector'].values))

# Create new columns for the principal components
tekmart_df['PC1'] = sentence_vectors_2d[:, 0]
tekmart_df['PC2'] = sentence_vectors_2d[:, 1]

# Graph results
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 8))
plt.scatter(tekmart_df['PC1'], tekmart_df['PC2'])
plt.xlabel("PC1")
plt.ylabel("PC2")
plt.title("PCA of Sentence Vectors")
plt.show()

tekmart_df["Customer_Review"] = tekmart_df["Customer_Review"].replace("n/a", np.nan)

# Remove rows where the column is now NaN
clean_df = tekmart_df.dropna(subset=["Customer_Review"])

from sklearn.cluster import KMeans

kmeans = KMeans(n_clusters=3, random_state=0)  # You can change n_clusters
clean_df['cluster'] = kmeans.fit_predict(clean_df[['PC1', 'PC2']])

import matplotlib.pyplot as plt
import matplotlib.colors as mcolors
import numpy as np

color_start = (185/255, 221/255, 241/255)   # light
color_end   = (42/255, 87/255, 131/255)    # darker

custom_cmap = mcolors.LinearSegmentedColormap.from_list(
    "custom_gradient", [color_start, color_end]
)

plt.figure(figsize=(10, 8))
plt.scatter(
    clean_df["PC1"],
    clean_df["PC2"],
    c=clean_df["cluster"],   # cluster labels
    cmap=custom_cmap
)
plt.xlabel("PC1")
plt.ylabel("PC2", rotation=0)
plt.title("Customer Reviews of High, Medium, and Low Satisfaction", fontsize=20, pad=20)
plt.colorbar(label="Cluster")


for cluster_num in __builtins__.range(3):
    cluster_reviews = clean_df[clean_df['cluster'] == cluster_num]['Customer_Review']
    print(f"Cluster {cluster_num}:")

    # sample only if enough rows exist
    sample_n = min(10, len(cluster_reviews))

    for i, review in enumerate(cluster_reviews.sample(n=sample_n, random_state=1)):
        print(f"  Example {i+1}: {review}")

    print("-" * 20)
plt.savefig("clusters_plot.jpg", dpi=300, bbox_inches="tight")
plt.show()

"""cluster 0 = bad reviews
cluster 1 = very good reviews
cluster 2 = average reviews

Which product types appear the most in each cluster? (curious to see if anything of note)
"""

cluster1 = clean_df[clean_df["Clusters"] == 1]
cluster1["first_word"].value_counts().idxmax()

cluster2 = clean_df[clean_df["Clusters"] == 2]
cluster2["first_word"].value_counts().idxmax()

cluster0 = clean_df[clean_df["Clusters"] == 0]
cluster0["first_word"].value_counts().idxmax()

"""creating a DF that takes out any rows with empty satisfaction notes"""

clean_df["Clusters"] = kmeans.labels_
clean_df = clean_df.drop("Galaxy", axis=1)
clean_df.to_csv("clustered_customer_reviews.csv")

cluster0_key_years= clean_df[
    (clean_df["Clusters"]==0) &
    (clean_df["Year"].isin([2021, 2022, 2023]))
]

cluster0_key_years.to_csv("cluster0_key_years.csv")

cluster0_key_years["Product_Types"].value_counts()

cluster0_key_years["first_word"].value_counts()
#this tells us that USBs, Mi, then Power Banks had the most negative reviews from 2021-2023

worst_reviews_df = cluster0_key_years[
    (cluster0_key_years["first_word"].isin(["USB","Mi","Power"]))
]
print(worst_reviews_df)
worst_reviews_df.to_csv("worst_reviews_df.csv")

"""--------

"""